import { readFileSync } from 'fs';
import { strict as assert } from 'assert';
const html = readFileSync('./index.html', 'utf8');
assert.ok(html.includes('<title>'), 'should have title tag');
assert.ok(html.includes('Micro Center') || html.includes('Stillwater'), 'title references campaign');
assert.ok(html.includes('id="boot"') || html.includes("id='boot'"), 'boot screen exists');
assert.ok(html.includes('boot-terminal'), 'boot terminal exists');
assert.ok(html.includes('hero'), 'hero section exists');
assert.ok(html.includes('Bring'), 'hero contains campaign headline');
assert.ok(html.includes('index.html'), 'nav links to index');
assert.ok(html.includes('market.html'), 'nav links to market');
assert.ok(html.includes('campaign.html'), 'nav links to campaign');
assert.ok(html.includes('Blake Harrison'), 'attributed to Blake Harrison');
assert.ok(html.includes('Market Opportunity') || html.includes('market-opportunity'), 'market opportunity section exists');
assert.ok(html.includes('27,655') || html.includes('27655'), 'accurate OSU enrollment stat');
assert.ok(html.includes('49,500') || html.includes('Growing Population'), 'population data present');
assert.ok(html.includes('3.82') || html.includes('economic'), 'economic data present');
assert.ok(html.includes('<footer>'), 'footer exists');
assert.ok(html.includes('OSU'), 'footer references OSU');
console.log('✓ All index.html tests passed (16/16)');
