import { readFileSync } from 'fs';
import { strict as assert } from 'assert';
const html = readFileSync('./market.html', 'utf8');
assert.ok(html.includes('<title>'), 'should have title tag');
assert.ok(html.includes('Retail Gap') || html.includes('Market') || html.includes('Stillwater'), 'title references page');
assert.ok(html.includes('Cole Sherer'), 'attributed to Cole Sherer');
assert.ok(html.includes('index.html'), 'nav links to index');
assert.ok(html.includes('market.html'), 'nav links to market');
assert.ok(html.includes('campaign.html'), 'nav links to campaign');
assert.ok(html.includes('Retail Gap') || html.includes('id="nearest"'), 'retail gap section exists');
assert.ok(html.includes('Dallas'), 'nearest location Dallas mentioned');
assert.ok(html.includes('210') || html.includes('miles'), 'distance data present');
assert.ok(html.includes('0') && html.includes('Oklahoma'), 'zero locations in Oklahoma mentioned');
assert.ok(html.includes('distance-card') || html.includes('nearest'), 'distance cards present');
assert.ok(html.includes('Best Buy') || html.includes('local'), 'local alternatives described');
assert.ok(html.includes('<footer>'), 'footer exists');
assert.ok(html.includes('Cole Sherer'), 'footer credits Cole');
console.log('✓ All market.html tests passed (14/14)');
